# Python

Python does not have built-in array manipulation. Therefore, in a 1d array cases, you can simply use a list to perform such task. Python has two kinds list implementation

1. list 
2. Tuple

They are slightly different, and will be elaborated in the following paragraphs


## List

List is the basic data type in programming language to create a new empty list (Noted I do not use the word declare) you can

In [46]:
myList=[]
myList

[]

### List function: len

To get the length of List you should 

In [47]:
len(myList)

0

### List method: insert and append

The python list implement all fundamental list method. If we wants to add the element to the list we can use insert or append.

Append add the new element at the end of the list

In [29]:
myList.append(1)
myList

[1]

insert takes two argument insert(location, value)

In [30]:
myList.insert(0,3)
myList

[3, 1]

### List indexing
We can find that the list follows common index rule.

| MyList | 3 | 1 |
| ----------- | ----------- | ----------- |
| Index | 0 | 1 |
| Negative index | -2 | -1 |

### List method: remove, pop, del

del delete the element

In [31]:
myList=[0,1,2,3]
del myList[2]
myList

[0, 1, 3]

pop remove the indexed item

In [32]:
myList=[0,1,2,3]
myList.pop(2)
myList

[0, 1, 3]

remove removes the first element that is the given value

In [33]:
myList=[0,1,2,3,2,3]
myList.remove(3)
myList

[0, 1, 2, 2, 3]

### List operation + and *

You should be aware that python does not implement array by default. Therefore, all the mathematical symbols operation in the list are all list operation

- +: concatenate

In [36]:
myList=[0,1,2]
nextList=[3,4,5]
myList+nextList

[0, 1, 2, 3, 4, 5]

- *:  repeat the elements multiple times

In [37]:
[1]*3

[1, 1, 1]

### List slicing

List slicing by using indexes separated by a colon [x : y], if you did not specify either x or y it will take it as start/end of array

In [38]:
myList=[0,1,2,3,4,5]
myList[2:4]

[2, 3]

In [41]:
myList[-4:-2]

[2, 3]

In [42]:
myList[1:]

[1, 2, 3, 4, 5]

In [43]:
myList[:4]

[0, 1, 2, 3]

### List comprehension

List comprehension is python's unique way to declare a list. It is inspired from the math set-built notation

$$
\{x | x < 0 \}
$$

Therefore in Python the expression is structured as List= [ {output expression} for {input} if {(Optional)condition}]

In [48]:
[2*i+1 for i in range(10) if i%2 is 0]

[1, 5, 9, 13, 17]

The above list only calclate 2*i+1 if i is an even number

## Tuple

Tuple is a "static" type of list. It is enclosed by "()". The dict is also a extension of tuple. It is usually used for multiple output of a function  

## Numpy array

A commonly used in maathematic, statistic implementationf of arrat is numpy array. You need yo import numpy library before using it

In [1]:
import numpy as np

np is a commonly used accronym of numpy. It is okay if you want to use other names 

### Create ndarray
There are 5 general mechanisms for creating arrays:
1. Conversion from other Python structures (e.g., lists, tuples)
2. Intrinsic numpy array creation objects (e.g., arange, ones, zeros, etc.)
3. Reading arrays from disk, either from standard or custom formats
4. Creating arrays from raw bytes through the use of strings or buffers
5. Use of special library functions (e.g., random)

#### Conversion from other Python structures
In general, numerical data arranged in an array-like structure in Python can be converted to arrays through the use of the array() function. 

In [2]:
np.array([2,3,1,0])


array([2, 3, 1, 0])

In [3]:
np.array([[1,2.0],[0,0],(1+1j,3.)]) ## This mix list and tuple

array([[1.+0.j, 2.+0.j],
       [0.+0.j, 0.+0.j],
       [1.+1.j, 3.+0.j]])

#### Intrinsic numpy array creation objects
NumPy has built-in functions for create empty arrays. This kind of cratetion usually takes a tuple indicating its dimension and shapes. This way is similar in Matlab environment.

In [4]:
np.zeros(2)

array([0., 0.])

In [5]:
np.ones((2, 3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [6]:
np.arange(2, 3, 0.1)

array([2. , 2.1, 2.2, 2.3, 2.4, 2.5, 2.6, 2.7, 2.8, 2.9])

In [7]:
np.indices((2,2,2))

array([[[[0, 0],
         [0, 0]],

        [[1, 1],
         [1, 1]]],


       [[[0, 0],
         [1, 1]],

        [[0, 0],
         [1, 1]]],


       [[[0, 1],
         [0, 1]],

        [[0, 1],
         [0, 1]]]])

In [8]:
np.linspace(1., 4., 6)

array([1. , 1.6, 2.2, 2.8, 3.4, 4. ])

### Common attributes
#### size, len, shape
This few methods we start through myArray=np.array([[1,2],[3,4]])

In [9]:
myArray=np.array([[1,2],[3,4]])

##### size
This attribute returns total elements in the array

In [10]:
myArray.size

4

##### len
This function returns total rows in the array

In [11]:
len(myArray)

2

##### shape
This attribute returns a tuple which indicates the dimension of this array

In [12]:
myArray.shape

(2, 2)

### np array operation

All arithmetic symbols operate on nparray are element-wise operation. (This is different from most of the mathematical programming languages).

Noted that most np function accept you take list as legal input (still it will ouput an np array), but keeping in mind that operater overloading and np.array method are not implemented on list data type.  

In [13]:
np.zeros((2,2)) + np.array([[1,2],[3,4]])

array([[1., 2.],
       [3., 4.]])

In [14]:
np.zeros((2,2)) - np.array([[1,2],[3,4]])

array([[-1., -2.],
       [-3., -4.]])

In [15]:
np.ones((2,2)) *  np.array([[1,2],[3,4]])

array([[1., 2.],
       [3., 4.]])

In [16]:
np.ones((2,2)) /  np.array([[1,2],[3,4]])

array([[1.        , 0.5       ],
       [0.33333333, 0.25      ]])

#### Brodcasting
Due to this feature, if the dimension of one array is less than the other, np array will brodcast the operation if the size is matched.

The following code will add/multiply [2,3] elementwise at each row 

In [17]:
np.array([2,3]) +  np.array([[1,2],[3,4]])

array([[3, 5],
       [5, 7]])

In [18]:
np.array([2,3]) * np.array([[1,2],[3,4]])

array([[ 2,  6],
       [ 6, 12]])

The following code will add [2,3] elementwise at each column 

In [19]:
np.array([[2],[3]]) + np.array([[1,2],[3,4]])

array([[3, 4],
       [6, 7]])

The following code will times 9 one each element.

In [20]:
9*np.ones((2,2))

array([[9., 9.],
       [9., 9.]])

#### Mathematical operation

Here are some commonly used mathematical operation
##### Dot operation
np.dot(a,b) do the dot product a*b
np.vdot.dot(a,b) do the dot product a*b

In [21]:
np.dot(np.array([1,0]),np.array([0,1])) ## (1,0) and (0,1) are orthognal so their dot product is zero

0

Noted that the dimension matters in the dot product

In [22]:
np.dot(np.array([1,0]),np.array([[0,1]])) ## (1,0) and ((0,1)) they are dimensional;y not correct

ValueError: shapes (2,) and (1,2) not aligned: 2 (dim 0) != 1 (dim 0)

However, vdot takes the input as vector so it does not matter in such case

In [23]:
np.vdot(np.array([1,0]),np.array([[0,1]])) ## (1,0) and (0,1) are orthognal so their dot product is zero

0

For high dimension dot you will need np.inner(), it will take sum-product over the last dimension 

In [24]:
np.inner(np.array([[1,2], [3,4]]) , np.array([[11, 12], [13, 14]]) ) 

array([[35, 41],
       [81, 95]])

so the ouput[0,0] is sum(a[0,:] * b[0,:]) ouput[0,1] is sum(a[0,:] * b[1,:]) and so on so forth

##### Matrix multiplication
np.matmul(a,b) is the matrix multiplication of matrix a and b. Therefore the dimension of the a's last dimension should be matched with the first dimension of b

In [25]:
a = [[1,0],[0,1]] ##It is an identity matrix
b = [[1,2,3],[4,5,6]] 

print(np.matmul(a,b))

[[1 2 3]
 [4 5 6]]


if either argument is 1-D array, it will be expanded to matrix by appending the last dimension and removed after multiplication.

In [38]:
a = [[1,0],[0,1]] 
b = [1,2] 
print(np.matmul(a,b))
print(np.matmul(b,a))

<class 'numpy.ndarray'>
[1 2]


##### Solving linear system
Suppose we have a linear system $Ax=B$ format then numpy can solve it by np.linalg.solve(A,B)

The follow example
$$
\begin{cases} 3x + 5y = 0 \\ 7x – 2y + 4z = 2 \\ x + 3y + 2z =4 \end{cases}
$$

In [27]:
np.linalg.solve([[3,5,0],[7,-2,4],[1,3,2]] ,[0,2,4])

array([-0.6122449 ,  0.36734694,  1.75510204])

##### Determinant
np.linalg.det(a) gives you the determinant 

In [28]:
np.linalg.det([[3,5,0],[7,-2,4],[1,3,2]])

-98.00000000000004

In [29]:
np.linalg.det([[1,3,5],[2,6,10],[3,9,15]])

0.0

##### Inverse
numpy.linalg.inv() gives you the inverse of the matrix

In [30]:
np.linalg.inv([[3,5,0],[7,-2,4],[1,3,2]])

array([[ 0.16326531,  0.10204082, -0.20408163],
       [ 0.10204082, -0.06122449,  0.12244898],
       [-0.23469388,  0.04081633,  0.41836735]])

In [31]:
np.linalg.inv([[1,3,5],[2,6,10],[3,9,15]]) ## This is a singular matrix, so it will return error 

LinAlgError: Singular matrix

##### Transpose 
you can either use function np.transpose or the array method array.T to do transpose

In [99]:
np.array([[1,2],[3,4]]).T

array([[1, 3],
       [2, 4]])

In [100]:
np.transpose(np.array([[1,2],[3,4]]))

array([[1, 3],
       [2, 4]])

#### Array manipulation

We start at a 2D np.array([[1,2],[3,4]]) and show some common manipulation method

In [97]:
myArray=np.array([[1,2],[3,4]])

##### reshape([dim])

The reshape method reshape the dimension of the array to expand/shrink the matrix

In [91]:
myArray.reshape((1,4))

array([[1, 2, 3, 4]])

If one of the dimension size is not known or varies over time you can sue -1 to insicate that Numpy will handle it.

In [94]:
myArray.reshape((1,-1))

array([[1, 2, 3, 4]])

In [101]:
myArray.reshape((1,2,-1))

array([[[1, 2],
        [3, 4]]])

#### I/O

You can save your ndarray by np.save().
It will create an .npy file fin the current directory
and you can read it by np.load()

In [86]:
np.save('my_data',np.array([1,0]))

In [87]:
np.load('my_data.npy')

array([1, 0])