# Python

Python does not have built-in array manipulation. Therefore, in a 1d array cases, you can simply use a list to perform such task. Python has two kinds list implementation

1. list 
2. Tuple

They are slightly different, and will be elaborated in the following paragraphs


## List

List is the basic data type in programming language to create a new empty list (Noted I do not use the word declare) you can

In [46]:
myList=[]
myList

[]

### List function: len

To get the length of List you should 

In [47]:
len(myList)

0

### List method: insert and append

The python list implement all fundamental list method. If we wants to add the element to the list we can use insert or append.

Append add the new element at the end of the list

In [29]:
myList.append(1)
myList

[1]

insert takes two argument insert(location, value)

In [30]:
myList.insert(0,3)
myList

[3, 1]

### List indexing
We can find that the list follows common index rule.

| MyList | 3 | 1 |
| ----------- | ----------- | ----------- |
| Index | 0 | 1 |
| Negative index | -2 | -1 |

### List method: remove, pop, del

del delete the element

In [31]:
myList=[0,1,2,3]
del myList[2]
myList

[0, 1, 3]

pop remove the indexed item

In [32]:
myList=[0,1,2,3]
myList.pop(2)
myList

[0, 1, 3]

remove removes the first element that is the given value

In [33]:
myList=[0,1,2,3,2,3]
myList.remove(3)
myList

[0, 1, 2, 2, 3]

### List operation + and *

You should be aware that python does not implement array by default. Therefore, all the mathematical symbols operation in the list are all list operation

- +: concatenate

In [36]:
myList=[0,1,2]
nextList=[3,4,5]
myList+nextList

[0, 1, 2, 3, 4, 5]

- *:  repeat the elements multiple times

In [37]:
[1]*3

[1, 1, 1]

### List slicing

List slicing by using indexes separated by a colon [x : y], if you did not specify either x or y it will take it as start/end of array

In [38]:
myList=[0,1,2,3,4,5]
myList[2:4]

[2, 3]

In [41]:
myList[-4:-2]

[2, 3]

In [42]:
myList[1:]

[1, 2, 3, 4, 5]

In [43]:
myList[:4]

[0, 1, 2, 3]

### List comprehension

List comprehension is python's unique way to declare a list. It is inspired from the math set-built notation

$$
\{x | x < 0 \}
$$

Therefore in Python the expression is structured as List= [ {output expression} for {input} if {(Optional)condition}]

In [48]:
[2*i+1 for i in range(10) if i%2 is 0]

[1, 5, 9, 13, 17]

The above list only calclate 2*i+1 if i is an even number

## Tuple

Tuple is a "static" type of list. It is enclosed by "()". The dict is also a extension of tuple. It is usually used for multiple output of a function  

## Numpy array

A commonly used in maathematic, statistic implementationf of arrat is numpy array. You need yo import numpy library before using it

In [50]:
import numpy as np

np is a commonly used accronym of numpy. It is okay if you want to use other names 

### Create ndarray
There are 5 general mechanisms for creating arrays:
1. Conversion from other Python structures (e.g., lists, tuples)
2. Intrinsic numpy array creation objects (e.g., arange, ones, zeros, etc.)
3. Reading arrays from disk, either from standard or custom formats
4. Creating arrays from raw bytes through the use of strings or buffers
5. Use of special library functions (e.g., random)

#### Conversion from other Python structures
In general, numerical data arranged in an array-like structure in Python can be converted to arrays through the use of the array() function. 

In [54]:
np.array([2,3,1,0])


array([2, 3, 1, 0])

In [55]:
np.array([[1,2.0],[0,0],(1+1j,3.)]) ## This mix list and tuple

array([[1.+0.j, 2.+0.j],
       [0.+0.j, 0.+0.j],
       [1.+1.j, 3.+0.j]])

#### Intrinsic numpy array creation objects
NumPy has built-in functions for create empty arrays. This kind of cratetion usually takes a tuple indicating its dimension and shapes. This way is similar in Matlab environment.

In [57]:
np.zeros(2)

array([0., 0.])

In [58]:
np.ones((2, 3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [62]:
np.arange(2, 3, 0.1)

array([2. , 2.1, 2.2, 2.3, 2.4, 2.5, 2.6, 2.7, 2.8, 2.9])

In [65]:
np.indices((2,2,2))

array([[[[0, 0],
         [0, 0]],

        [[1, 1],
         [1, 1]]],


       [[[0, 0],
         [1, 1]],

        [[0, 0],
         [1, 1]]],


       [[[0, 1],
         [0, 1]],

        [[0, 1],
         [0, 1]]]])

In [66]:
np.linspace(1., 4., 6)

array([1. , 1.6, 2.2, 2.8, 3.4, 4. ])